/**
 * The conversation states the avatar reacts to, and the mapping from the voice
 * session's own `Mode`. Kept separate from the R3F components so the page can
 * import it without pulling three.js into the initial bundle.
 */

import type { Mode } from "@/hooks/useVoiceSession";

export type AvatarState = "idle" | "listening" | "thinking" | "speaking";

/** "paused" holds the at-rest idle pose — the session is up but nothing is moving. */
export function avatarStateFor(mode: Mode): AvatarState {
  switch (mode) {
    case "listening":
      return "listening";
    case "thinking":
      return "thinking";
    case "speaking":
      return "speaking";
    default:
      return "idle";
  }
}

/**
 * Where the avatar lives, served from frontend/public.
 *
 * This points at the PRE-COMPRESSED file on purpose. Next compresses responses
 * on the fly, which means it cannot know the body length in advance and answers
 * `Transfer-Encoding: chunked` with no Content-Length and no Accept-Ranges. For
 * a 30MB model behind a reverse proxy that is the difference between a download
 * and a hang: no total to show progress against, a proxy streaming a body of
 * unknown size into its own read timeout, and no way to resume a dropped
 * connection because ranged requests are refused.
 *
 * Served as a static .gz with an explicit Content-Encoding (see next.config.ts)
 * the same bytes go out with Content-Length and Accept-Ranges, and the browser
 * inflates them transparently — GLTFLoader still sees a plain .glb.
 *
 * Both files are generated by scripts/optimize_glb.py; keep them in step.
 */
export const AVATAR_MODEL_URL = "/models/girl15.glb.gz";
