"""Hand-tuned Urdu → English tables for query expansion (see expansion.py).

Tuned against this knowledge base; the eval set measured them at fifteen points of
hit@5 on Urdu questions. Multi-word terms go in PHRASES, single words in GLOSSARY.
"""

from __future__ import annotations

# Words in nearly every section of the corpus, which carry no signal.
KB_STOPWORDS = {
    "the", "and", "for", "with", "that", "this", "are", "was", "will", "from", "has",
    "have", "its", "not", "you", "your", "our", "who", "what", "when", "where", "how",
    "can", "does", "did", "any", "all", "also", "more", "than", "about", "into", "over",
    "mari", "marienergies", "energies", "pakistan", "company", "limited",
}

# Urdu grammatical particles, stripped so "کیا" alone does not expand a question.
UR_STOPWORDS = {
    "میں", "کا", "کی", "کے", "کو", "سے", "پر", "ہے", "ہیں", "ہو", "تھا", "تھی", "اور",
    "یا", "بھی", "تو", "نے", "ایک", "یہ", "وہ", "کیا", "کون", "کیسے", "کیوں", "کہاں",
    "براہ", "کرم", "مجھے", "ہمیں", "آپ", "بتائیے", "بتائیں", "بتاؤ", "سکتے", "سکتی",
}

# Urdu spells acronyms letter by letter ("پی ایس ایکس" = P-S-X), so the phrase is matched
# before its single letters can collide with unrelated words.
PHRASES: dict[str, str] = {
    "سی ای او": "ceo managing director chief executive leadership",
    "ایم ڈی": "managing director ceo leadership",
    "ای میل": "contact email investor relations",
    "ڈیٹا سینٹر": "data center technologies sky47 subsidiary",
    "جی پی یو": "gpu as a service gpuaas ascend nvidia clusters ai farm sky47",
    "جی پی یوز": "gpu as a service gpuaas ascend nvidia clusters ai farm sky47",
    "اے آئی فارم": "cloud ai farm gpu as a service sky47 ai",
    "اسلام آباد": "islamabad head office contact",
    "اے آئی": "artificial intelligence digital transformation technology",
    "مصنوعی ذہانت": "artificial intelligence digital transformation technology",
    "تیل اور گیس": "oil gas upstream exploration production",
    "قدرتی گیس": "gas production reserves field",
    "اسٹاک ایکسچینج": "psx listed shares market capitalization",
    "منافع": "profit financial performance earnings",
    "ماری گیس فیلڈ": "mari gas field daharki discovery",
    "ری نیو ایبل": "renewable solar energy transition",
    "ہیڈ آفس": "head office contact address islamabad",
    "آف شور": "offshore exploration expansion",
    "سرمایہ کار": "investor relations shareholders",
    "بورڈ آف ڈائریکٹرز": "board directors governance",
    "ری برانڈنگ": "rebranding identity logo mari petroleum",
    "منافع منقسمہ": "dividend per share payout",
    "سرمایہ کاری": "investor relations investment",
    "ای ایس جی": "esg sustainability governance",
    "سی ایس آر": "csr community initiatives welfare",
}

GLOSSARY: dict[str, str] = {
    # company, identity, ownership
    "کمپنی": "company overview legal entity",
    "ادارہ": "company overview",
    "تعارف": "overview about",
    "ملکیت": "ownership shareholding shareholders",
    "مالک": "ownership shareholding parent",
    "حصص": "shareholding shares shareholders free float",
    "شیئر": "shareholding shares stock price psx",
    "شیئرہولڈر": "shareholders shareholding structure",
    "فوجی": "fauji foundation shareholding",
    "حکومت": "government pakistan shareholding ogdcl",
    "ذیلی": "subsidiaries group structure equity",
    "کمپنیاں": "subsidiaries associated companies group",
    "ماری": "marienergies mari petroleum mpcl",
    "نام": "rebranding name mari petroleum",
    "تاریخ": "history timeline milestones",
    "بانی": "history establishment discovery",
    # leadership and governance
    "سربراہ": "ceo managing director leadership",
    "چیئرمین": "chairman board directors",
    "قیادت": "leadership management team executives",
    "انتظامیہ": "senior management team leadership",
    "ٹیم": "management team board members",
    "بورڈ": "board directors governance committees",
    "کمیٹی": "board committees audit governance",
    "گورننس": "governance board committees compliance",
    # business, operations, exploration
    "کاروبار": "principal business activities verticals",
    "خدمات": "services mari services drilling seismic",
    "سروس": "services mari services drilling seismic",
    "شعبے": "verticals business segments diversification",
    "تیل": "oil liquids production upstream",
    "گیس": "gas production reserves field",
    "کنواں": "wells drilling program",
    "کھدائی": "drilling program wells",
    "دریافت": "discoveries exploration hydrocarbon",
    "تلاش": "exploration portfolio blocks",
    "بلاک": "exploration blocks acreage",
    "پیداوار": "production sales capacity",
    "ذخائر": "reserves resources mmboe",
    "فیلڈ": "field development mari gas field daharki",
    "معدنیات": "minerals copper gold rare earth",
    "کان": "minerals mining copper gold",
    "ٹیکنالوجی": "technology digital transformation data center",
    "ڈیٹا": "data center technologies digital",
    "سینٹر": "data center technologies sky47",
    "کلاؤڈ": "cloud high performance computing infrastructure",
    "ڈیجیٹل": "digital transformation technology automation",
    # financials
    "منافع": "profit earnings financial performance",
    "آمدنی": "net sales revenue financial performance",
    "مالی": "financial performance results reports",
    "سرمایہ": "market capitalization investment",
    "ڈیویڈنڈ": "dividend per share payout",
    "ٹیکس": "taxation national exchequer contribution",
    "قیمت": "stock price share price psx",
    # sustainability, people, community
    "ماحول": "environment sustainability esg emissions",
    "پائیداری": "sustainability esg environment",
    "توانائی": "energy transition renewable power",
    "شمسی": "solar renewable energy project",
    "ملازمت": "careers jobs recruitment hiring",
    "نوکری": "careers jobs recruitment hiring",
    "بھرتی": "recruitment process careers",
    "تربیت": "training talent development learning",
    "ملازمین": "workforce employees headcount",
    "خواتین": "diversity inclusion women workforce",
    "فلاح": "csr community welfare initiatives",
    "تعلیم": "education csr schools scholarships",
    "صحت": "healthcare csr medical camps",
    "کھیل": "sports sponsorship csr",
    # contact
    "رابطہ": "contact address email website phone",
    "پتہ": "contact address head office location",
    "فون": "contact phone number",
    "ویب": "website contact",
    "دفتر": "office head office karachi quetta",
    "کراچی": "karachi office contact",
    "کوئٹہ": "quetta office contact",
    # transliterated English, which visitors use more often than the formal Urdu word
    "ریکروٹمنٹ": "recruitment process careers hiring",
    "پروسیس": "process procedure steps",
    "جاب": "careers jobs vacancies",
    "جابز": "careers jobs vacancies",
    "کیریئر": "careers jobs recruitment",
    "انٹرویو": "interview recruitment process",
    "اپلائی": "apply application recruitment careers",
    "درخواست": "application apply recruitment",
    "ٹریننگ": "training talent development",
    "پروفٹ": "profit earnings financial performance",
    "ریونیو": "net sales revenue financial performance",
    "شیئرز": "shares shareholding psx",
    "اسٹاک": "stock price psx shares",
    "مارکیٹ": "market capitalization psx",
    "ڈائریکٹر": "directors board governance",
    "منیجمنٹ": "management team leadership",
    "لیڈرشپ": "leadership management team",
    "سبسڈری": "subsidiaries group structure",
    "پروڈکشن": "production capacity output",
    "ایکسپلوریشن": "exploration blocks portfolio",
    "ڈرلنگ": "drilling wells program",
    "ریزروز": "reserves resources",
    "منرلز": "minerals copper gold rare earth",
    "کاپر": "copper minerals mining",
    "گولڈ": "gold minerals mining",
    "سولر": "solar renewable energy",
    "کنٹیکٹ": "contact address phone email",
    "سپلائر": "supplier hub vendors procurement",
    "ویکنسی": "vacancies careers jobs",
    # gaps found by sweeping every KB section with realistic Urdu questions
    "آڈیٹر": "auditors external ferguson",
    "ریٹنگ": "credit rating",
    "کریڈٹ": "credit rating",
    "ورٹیکل": "verticals business segments",
    "ورٹیکلز": "verticals business segments",
    "سکائی": "sky47 technologies data center",
    "کلسٹر": "gpu clusters ascend nvidia ai infrastructure",
    "کلسٹرز": "gpu clusters ascend nvidia ai infrastructure",
    "فارم": "cloud ai farm gpu service sky47 ai",
    "آفشور": "offshore exploration expansion",
    "سمندری": "offshore exploration",
    "کنویں": "wells drilling program",
    "دریافتیں": "discoveries hydrocarbon wells",
    "سیلز": "net sales revenue",
    "فروخت": "net sales revenue",
    "درخت": "trees plantation environment",
    "شجرکاری": "trees plantation environment",
    "فائدے": "benefits employer join us careers",
    "مراعات": "benefits compensation careers",
    "میل": "meal program nourish flourish",
    "کھانا": "meal program nutrition",
    "اعلان": "announcements recent developments",
    "اعلانات": "announcements recent developments",
    "تعداد": "workforce total employees figures",
    "انویسٹر": "investor relations queries",
    # generic
    "وژن": "vision mission",
    "مشن": "vision mission",
    "مقصد": "vision mission values purpose",
    "اقدار": "core values integrity unity excellence",
    "گاہک": "customers fertilizer buyers",
    "صارف": "customers fertilizer buyers",
    "کھاد": "fertilizer feed gas customers",
    "کب": "timeline history milestones date",
    "کتنا": "figures quick reference capacity",
}

# Letter names, to join a spelled-out run back into its acronym.
URDU_LETTER_NAMES = {
    "اے": "a", "بی": "b", "سی": "c", "ڈی": "d", "ای": "e", "ایف": "f", "جی": "g",
    "ایچ": "h", "آئی": "i", "جے": "j", "کے": "k", "ایل": "l", "ایم": "m", "این": "n",
    "او": "o", "پی": "p", "کیو": "q", "آر": "r", "ایس": "s", "ٹی": "t", "یو": "u",
    "وی": "v", "ڈبلیو": "w", "ایکس": "x", "وائے": "y", "زیڈ": "z",
}

# Urdu letter → Latin sound, for matching proper nouns by sound.
URDU_TO_LATIN = {
    "ا": "a", "آ": "a", "ب": "b", "پ": "p", "ت": "t", "ٹ": "t", "ث": "s", "ج": "j",
    "چ": "ch", "ح": "h", "خ": "kh", "د": "d", "ڈ": "d", "ذ": "z", "ر": "r", "ڑ": "r",
    "ز": "z", "ژ": "zh", "س": "s", "ش": "sh", "ص": "s", "ض": "z", "ط": "t", "ظ": "z",
    "ع": "a", "غ": "gh", "ف": "f", "ق": "k", "ک": "k", "گ": "g", "ل": "l", "م": "m",
    "ن": "n", "ں": "n", "و": "w", "ہ": "h", "ھ": "h", "ء": "", "ی": "y", "ے": "e",
    "ئ": "y", "ؤ": "w", "أ": "a", "ۃ": "h", "ة": "h",
}

assert not [k for k in GLOSSARY if " " in k], "multi-word GLOSSARY key: use PHRASES"
